### ISSUE TITLE
Error: Too many levels of symbolic links (v1.7.0)

### ISSUE THREAD

**Issue by agmond** [Checkmarx/kics#6413]
When running KICS v1.7.0, I'm getting the following error:
```
Preparing Scan Assets:  \Error: failed to open excluded file: stat /code/deploy/deploy: too many levels of symbolic links
```
Not that I'm using v1.7.0 after reverting back from v1.7.1 due to #6381.

**Comment by gabriel-cx** [comment]
Hi @agmond,

Kindly notice that https://github.com/Checkmarx/kics/issues/6381 is already solved.
If you use KICS latest version [(v1.7.3)](https://github.com/Checkmarx/kics/releases/tag/v1.7.3) it should resolve this problem.

I'm closing this issue but feel free to re-open it or create a new one if the same or new issue appears.

**Comment by agmond** [comment]
Thank you @gabriel-cx!

**Comment by ike** [comment]
Hey there, I am experiencing somthing which seems similar, but on gitlab itself. Is this related? 

[gitlab issue describing problem in v4.1.3](https://gitlab.com/gitlab-org/gitlab/-/issues/419053)

**Comment by cxMiguelSilva** [comment]
> Hey there, I am experiencing somthing which seems similar, but on gitlab itself. Is this related?
> 
> [gitlab issue describing problem in v1.7.3](https://gitlab.com/gitlab-org/gitlab/-/issues/419053)

Hi @ike,
Can you confirm that it is still occurring in the [latest release](https://github.com/Checkmarx/kics/releases/tag/v1.7.4) made yesterday?

**Comment by liorj-orca** [comment]
@cxMiguelSilva with the latest kics version (v1.7.4) when scanning https://github.com/madhuakula/kubernetes-goat for example, you still can the isssue
